name: test
channels:
  - conda-forge
  - nodefaults
dependencies:
    # Base
  - numpy
  - python
  - qcelemental
  - msgpack-python

    # Testing
  - pytest
  - pytest-cov
  - psi4 1.9.1
  - dftd3-python
  - codecov
